platform :ios, '9.0'

target 'test' do
  use_frameworks!
  
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'Masonry'
   pod 'MJRefresh'
   pod 'MJExtension'
   pod 'SVProgressHUD'
   pod 'IQKeyboardManager'
   pod 'HXPhotoPicker'

end
